In [25]:
# Lets now talk about other Pandas terminologies :

# 1. Like adding new column in Dataset.
# 2. Changing the data in particular column of dataset (update).
# 3. Remove the column in dataset.

import pandas as pd

Data = {
    'Name' : ["AbdulRehman", 'Fatima', 'Umar', "Taimur", "Javed", "Alexander", "Maria", "Miller", "Alex", "Zennat"],
    'Bank Name': ['Payoneer', 'UBL', 'Meezan', 'HBL', 'Askari', 'Payoneer', 'Payoneer', 'British Bank', 'National Bank Chicago', 'Meezan'],
    'Bank Account' : [237563, 234598, 237682, 346778, 8667321, 876626, 1237546, 8754456, 2314508, 86625591],
    'Age' : [23, 27, 26, 21, 26, 28, 23, 42, 47, 31],
    'Gender' : ['Male', 'Female', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female'],
    'Creation_Date' : ['23-04-2023', '24-07-2022', '09-05-2020', '12-08-2025', '17-12-2017', '02-04-2026', '18-03-2025', '21-10-2003', '13-11-2001', '05-04-2019']
}

df = pd.DataFrame(Data)

df

          Name              Bank Name  Bank Account  Age  Gender Creation_Date
0  AbdulRehman               Payoneer        237563   23    Male    23-04-2023
1       Fatima                    UBL        234598   27  Female    24-07-2022
2         Umar                 Meezan        237682   26    Male    09-05-2020
3       Taimur                    HBL        346778   21    Male    12-08-2025
4        Javed                 Askari       8667321   26    Male    17-12-2017
5    Alexander               Payoneer        876626   28    Male    02-04-2026
6        Maria               Payoneer       1237546   23  Female    18-03-2025
7       Miller           British Bank       8754456   42    Male    21-10-2003
8         Alex  National Bank Chicago       2314508   47    Male    13-11-2001
9       Zennat                 Meezan      86625591   31  Female    05-04-2019

In [26]:
# Now convert this DataFrame into csv file :

df.to_csv('DataSets&DataFiles/Bank_Accounts_Info.csv', index=False)

print(df)

          Name              Bank Name  Bank Account  Age  Gender Creation_Date
0  AbdulRehman               Payoneer        237563   23    Male    23-04-2023
1       Fatima                    UBL        234598   27  Female    24-07-2022
2         Umar                 Meezan        237682   26    Male    09-05-2020
3       Taimur                    HBL        346778   21    Male    12-08-2025
4        Javed                 Askari       8667321   26    Male    17-12-2017
5    Alexander               Payoneer        876626   28    Male    02-04-2026
6        Maria               Payoneer       1237546   23  Female    18-03-2025
7       Miller           British Bank       8754456   42    Male    21-10-2003
8         Alex  National Bank Chicago       2314508   47    Male    13-11-2001
9       Zennat                 Meezan      86625591   31  Female    05-04-2019

In [27]:
df2 = pd.read_csv('DataSets&DataFiles/Bank_Accounts_Info.csv')

df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           10 non-null     str
 1   Bank Name      10 non-null     str
 2   Bank Account   10 non-null     int64
 3   Age            10 non-null     int64
 4   Gender         10 non-null     str
 5   Creation_Date  10 non-null     str
dtypes: int64(2), str(4)
memory usage: 612.0 bytes

In [28]:
df2.describe()

       Bank Account        Age
count  1.000000e+01  10.000000
mean   1.095327e+07  29.400000
std    2.679959e+07   8.527081
min    2.345980e+05  21.000000
25%    2.649560e+05  23.750000
50%    1.057086e+06  26.500000
75%    7.079118e+06  30.250000
max    8.662559e+07  47.000000

In [29]:
# Inserting data at specific location or at the end(by default) :

# First insert at end position (by default) :

df2['Balance'] = [239800, 746000, 365366, 564700, 565360, 450000, 534900, 435000, 100, 637800]

print(df2)

          Name              Bank Name  Bank Account  Age  Gender  \
0  AbdulRehman               Payoneer        237563   23    Male
1       Fatima                    UBL        234598   27  Female
2         Umar                 Meezan        237682   26    Male
3       Taimur                    HBL        346778   21    Male
4        Javed                 Askari       8667321   26    Male
5    Alexander               Payoneer        876626   28    Male
6        Maria               Payoneer       1237546   23  Female
7       Miller           British Bank       8754456   42    Male
8         Alex  National Bank Chicago       2314508   47    Male
9       Zennat                 Meezan      86625591   31  Female

  Creation_Date  Balance
0    23-04-2023   239800
1    24-07-2022   746000
2    09-05-2020   365366
3    12-08-2025   564700
4    17-12-2017   565360
5    02-04-2026   450000
6    18-03-2025   534900
7    21-10-2003   435000
8    13-11-2001      100
9    05-04-2019   637800

In [30]:
# Insert at specific position (index) column :

# Like Syntax : df2.insert(loc, 'Column_Name', data)

df2.insert(2, 'Monthly_Tax2', ((df2['Balance']/100)*2))

print(df2)

          Name              Bank Name  Monthly_Tax2  Bank Account  Age  \
0  AbdulRehman               Payoneer       4796.00        237563   23
1       Fatima                    UBL      14920.00        234598   27
2         Umar                 Meezan       7307.32        237682   26
3       Taimur                    HBL      11294.00        346778   21
4        Javed                 Askari      11307.20       8667321   26
5    Alexander               Payoneer       9000.00        876626   28
6        Maria               Payoneer      10698.00       1237546   23
7       Miller           British Bank       8700.00       8754456   42
8         Alex  National Bank Chicago          2.00       2314508   47
9       Zennat                 Meezan      12756.00      86625591   31

   Gender Creation_Date  Balance
0    Male    23-04-2023   239800
1  Female    24-07-2022   746000
2    Male    09-05-2020   365366
3    Male    12-08-2025   564700
4    Male    17-12-2017   565360
5    Male    02-04-2026   450000
6  Female    18-03-2025   534900
7    Male    21-10-2003   435000
8    Male    13-11-2001      100
9  Female    05-04-2019   637800

In [31]:
df2.loc[8, 'Balance'] = 2500000

print(df2)

          Name              Bank Name  Monthly_Tax2  Bank Account  Age  \
0  AbdulRehman               Payoneer       4796.00        237563   23
1       Fatima                    UBL      14920.00        234598   27
2         Umar                 Meezan       7307.32        237682   26
3       Taimur                    HBL      11294.00        346778   21
4        Javed                 Askari      11307.20       8667321   26
5    Alexander               Payoneer       9000.00        876626   28
6        Maria               Payoneer      10698.00       1237546   23
7       Miller           British Bank       8700.00       8754456   42
8         Alex  National Bank Chicago          2.00       2314508   47
9       Zennat                 Meezan      12756.00      86625591   31

   Gender Creation_Date  Balance
0    Male    23-04-2023   239800
1  Female    24-07-2022   746000
2    Male    09-05-2020   365366
3    Male    12-08-2025   564700
4    Male    17-12-2017   565360
5    Male    02-04-2026   450000
6  Female    18-03-2025   534900
7    Male    21-10-2003   435000
8    Male    13-11-2001  2500000
9  Female    05-04-2019   637800

In [32]:
df2.loc[8, 'Monthly_Tax2'] = 2500000 * 0.02

print(df2)

          Name              Bank Name  Monthly_Tax2  Bank Account  Age  \
0  AbdulRehman               Payoneer       4796.00        237563   23
1       Fatima                    UBL      14920.00        234598   27
2         Umar                 Meezan       7307.32        237682   26
3       Taimur                    HBL      11294.00        346778   21
4        Javed                 Askari      11307.20       8667321   26
5    Alexander               Payoneer       9000.00        876626   28
6        Maria               Payoneer      10698.00       1237546   23
7       Miller           British Bank       8700.00       8754456   42
8         Alex  National Bank Chicago      50000.00       2314508   47
9       Zennat                 Meezan      12756.00      86625591   31

   Gender Creation_Date  Balance
0    Male    23-04-2023   239800
1  Female    24-07-2022   746000
2    Male    09-05-2020   365366
3    Male    12-08-2025   564700
4    Male    17-12-2017   565360
5    Male    02-04-2026   450000
6  Female    18-03-2025   534900
7    Male    21-10-2003   435000
8    Male    13-11-2001  2500000
9  Female    05-04-2019   637800

In [33]:
# Updating multiple values :

df2['Balance'] = df2['Balance'] + ((df2['Balance']/100) * 5) # But Alternative Formula : df2['Balance'] = df2['Balance'] * 1.05

print(df2)

          Name              Bank Name  Monthly_Tax2  Bank Account  Age  \
0  AbdulRehman               Payoneer       4796.00        237563   23
1       Fatima                    UBL      14920.00        234598   27
2         Umar                 Meezan       7307.32        237682   26
3       Taimur                    HBL      11294.00        346778   21
4        Javed                 Askari      11307.20       8667321   26
5    Alexander               Payoneer       9000.00        876626   28
6        Maria               Payoneer      10698.00       1237546   23
7       Miller           British Bank       8700.00       8754456   42
8         Alex  National Bank Chicago      50000.00       2314508   47
9       Zennat                 Meezan      12756.00      86625591   31

   Gender Creation_Date    Balance
0    Male    23-04-2023   251790.0
1  Female    24-07-2022   783300.0
2    Male    09-05-2020   383634.3
3    Male    12-08-2025   592935.0
4    Male    17-12-2017   593628.0
5    Male    02-04-2026   472500.0
6  Female    18-03-2025   561645.0
7    Male    21-10-2003   456750.0
8    Male    13-11-2001  2625000.0
9  Female    05-04-2019   669690.0

In [ ]:
# Then removing or drop the database :
df2.insert(2, 'Monthly_Tax2', [4796, 14920, 7307, 11294, 11307, 9000, 10698, 8700, 12700, 12756])

print(df2)

          Name              Bank Name  Monthly_Tax2  Monthly_Tax  \
0  AbdulRehman               Payoneer          4796      95.9200
1       Fatima                    UBL         14920     298.4000
2         Umar                 Meezan          7307     146.1464
3       Taimur                    HBL         11294     225.8800
4        Javed                 Askari         11307     226.1440
5    Alexander               Payoneer          9000     180.0000
6        Maria               Payoneer         10698     213.9600
7       Miller           British Bank          8700     174.0000
8         Alex  National Bank Chicago         12700     254.0000
9       Zennat                 Meezan         12756     255.1200

   Bank Account  Age  Gender Creation_Date    Balance
0        237563   23    Male    23-04-2023   251790.0
1        234598   27  Female    24-07-2022   783300.0
2        237682   26    Male    09-05-2020   383634.3
3        346778   21    Male    12-08-2025   592935.0
4       8667321   26    Male    17-12-2017   593628.0
5        876626   28    Male    02-04-2026   472500.0
6       1237546   23  Female    18-03-2025   561645.0
7       8754456   42    Male    21-10-2003   456750.0
8       2314508   47    Male    13-11-2001  2625000.0
9      86625591   31  Female    05-04-2019  1050000.0

In [34]:
# Then drop the column in dataset :

df2.drop(columns=['Monthly_Tax2'], inplace=True)

print(df2)

          Name              Bank Name  Bank Account  Age  Gender  \
0  AbdulRehman               Payoneer        237563   23    Male
1       Fatima                    UBL        234598   27  Female
2         Umar                 Meezan        237682   26    Male
3       Taimur                    HBL        346778   21    Male
4        Javed                 Askari       8667321   26    Male
5    Alexander               Payoneer        876626   28    Male
6        Maria               Payoneer       1237546   23  Female
7       Miller           British Bank       8754456   42    Male
8         Alex  National Bank Chicago       2314508   47    Male
9       Zennat                 Meezan      86625591   31  Female

  Creation_Date    Balance
0    23-04-2023   251790.0
1    24-07-2022   783300.0
2    09-05-2020   383634.3
3    12-08-2025   592935.0
4    17-12-2017   593628.0
5    02-04-2026   472500.0
6    18-03-2025   561645.0
7    21-10-2003   456750.0
8    13-11-2001  2625000.0
9    05-04-2019   669690.0

In [35]:
df2.insert(4, 'Monthy_Tax', df2['Balance'] * 0.02)

print(df2)

          Name              Bank Name  Bank Account  Age  Monthy_Tax  Gender  \
0  AbdulRehman               Payoneer        237563   23    5035.800    Male
1       Fatima                    UBL        234598   27   15666.000  Female
2         Umar                 Meezan        237682   26    7672.686    Male
3       Taimur                    HBL        346778   21   11858.700    Male
4        Javed                 Askari       8667321   26   11872.560    Male
5    Alexander               Payoneer        876626   28    9450.000    Male
6        Maria               Payoneer       1237546   23   11232.900  Female
7       Miller           British Bank       8754456   42    9135.000    Male
8         Alex  National Bank Chicago       2314508   47   52500.000    Male
9       Zennat                 Meezan      86625591   31   13393.800  Female

  Creation_Date    Balance
0    23-04-2023   251790.0
1    24-07-2022   783300.0
2    09-05-2020   383634.3
3    12-08-2025   592935.0
4    17-12-2017   593628.0
5    02-04-2026   472500.0
6    18-03-2025   561645.0
7    21-10-2003   456750.0
8    13-11-2001  2625000.0
9    05-04-2019   669690.0