In [2]:
# Now in this notebook I start working on handling missing values like finding missing value and then filling these rows of particular columns
# in dataset when values are missing.

import pandas as pd

In [3]:
df = pd.read_csv('DataSets&DataFiles/housing_dataset.csv')

print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.6 MB

In [5]:
# Then Now checking wheather my dataset have missing values :
df.isnull()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
20635,False,False,False,False,False,False,False,False,False,False
20636,False,False,False,False,False,False,False,False,False,False
20637,False,False,False,False,False,False,False,False,False,False
20638,False,False,False,False,False,False,False,False,False,False
20639,False,False,False,False,False,False,False,False,False,False

In [6]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [ ]:
# Now how we deal or handle these missing values in particular or any column of sataset :

# First either you drop the the particular columns or rows or records in that columns that have missing values in dataset by using dropna method :
# Only use this method if that particulat missing values or missing values containig rows are not important.

# Like first I add(insert) a column That in dataset that may have missing values but its not as important that I use it, So I drop them by using 
# dropna method :

# I use for this purpose Bank_Accounts_Info.csv file :

Data2 = {
    'Name' : ["AbdulRehman", 'Fatima', 'Umar', "Taimur", "Javed", "Alexander", "Maria", "Miller", "Alex", "Zennat"],
    'Bank Name': ['Payoneer', 'UBL', 'Meezan', 'HBL', 'Askari', 'Payoneer', 'Payoneer', 'British Bank', 'National Bank Chicago', 'Meezan'],
    'Bank Account' : [237563, 234598, 237682, 346778, 8667321, 876626, 1237546, 8754456, 2314508, 86625591],
    'Age' : [23, 27, 26, 21, 26, 28, 23, 42, 47, 31],
    'Status' : ['Single', None, 'Married', None, 'Single',None, 'Single', 'Single', 'Married', None],
    'Gender' : ['Male', 'Female', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female'],
    'Creation_Date' : ['23-04-2023', '24-07-2022', '09-05-2020', '12-08-2025', '17-12-2017', '02-04-2026', '18-03-2025', '21-10-2003', '13-11-2001', '05-04-2019']
}

df2 = pd.DataFrame(Data2)

print(df2)

          Name              Bank Name  Bank Account  Age   Status  Gender  \
0  AbdulRehman               Payoneer        237563   23   Single    Male
1       Fatima                    UBL        234598   27      NaN  Female
2         Umar                 Meezan        237682   26  Married    Male
3       Taimur                    HBL        346778   21      NaN    Male
4        Javed                 Askari       8667321   26   Single    Male
5    Alexander               Payoneer        876626   28      NaN    Male
6        Maria               Payoneer       1237546   23   Single  Female
7       Miller           British Bank       8754456   42   Single    Male
8         Alex  National Bank Chicago       2314508   47  Married    Male
9       Zennat                 Meezan      86625591   31      NaN  Female

  Creation_Date
0    23-04-2023
1    24-07-2022
2    09-05-2020
3    12-08-2025
4    17-12-2017
5    02-04-2026
6    18-03-2025
7    21-10-2003
8    13-11-2001
9    05-04-2019

In [8]:
df2.isnull().sum()

Name             0
Bank Name        0
Bank Account     0
Age              0
Status           4
Gender           0
Creation_Date    0
dtype: int64

In [ ]:
print(df2)

df2.dropna(axis = 0, inplace=False) # So because of inplace=False so this dropna method thats actually 
# drops that particular rows that have missing value in dataset.Its actually generates nes dataframe that cannot have that missing values rows
# but actual dataset stays unchangable because inplace=False not True.

          Name              Bank Name  Bank Account  Age   Status  Gender  \
0  AbdulRehman               Payoneer        237563   23   Single    Male
1       Fatima                    UBL        234598   27      NaN  Female
2         Umar                 Meezan        237682   26  Married    Male
3       Taimur                    HBL        346778   21      NaN    Male
4        Javed                 Askari       8667321   26   Single    Male
5    Alexander               Payoneer        876626   28      NaN    Male
6        Maria               Payoneer       1237546   23   Single  Female
7       Miller           British Bank       8754456   42   Single    Male
8         Alex  National Bank Chicago       2314508   47  Married    Male
9       Zennat                 Meezan      86625591   31      NaN  Female

  Creation_Date
0    23-04-2023
1    24-07-2022
2    09-05-2020
3    12-08-2025
4    17-12-2017
5    02-04-2026
6    18-03-2025
7    21-10-2003
8    13-11-2001
9    05-04-2019

,Name,Bank Name,Bank Account,Age,Status,Gender,Creation_Date
0,AbdulRehman,Payoneer,237563,23,Single,Male,23-04-2023
2,Umar,Meezan,237682,26,Married,Male,09-05-2020
4,Javed,Askari,8667321,26,Single,Male,17-12-2017
6,Maria,Payoneer,1237546,23,Single,Female,18-03-2025
7,Miller,British Bank,8754456,42,Single,Male,21-10-2003
8,Alex,National Bank Chicago,2314508,47,Married,Male,13-11-2001

In [14]:
print(df2)

df2.dropna(axis=1, inplace=False)

          Name              Bank Name  Bank Account  Age   Status  Gender  \
0  AbdulRehman               Payoneer        237563   23   Single    Male
1       Fatima                    UBL        234598   27      NaN  Female
2         Umar                 Meezan        237682   26  Married    Male
3       Taimur                    HBL        346778   21      NaN    Male
4        Javed                 Askari       8667321   26   Single    Male
5    Alexander               Payoneer        876626   28      NaN    Male
6        Maria               Payoneer       1237546   23   Single  Female
7       Miller           British Bank       8754456   42   Single    Male
8         Alex  National Bank Chicago       2314508   47  Married    Male
9       Zennat                 Meezan      86625591   31      NaN  Female

  Creation_Date
0    23-04-2023
1    24-07-2022
2    09-05-2020
3    12-08-2025
4    17-12-2017
5    02-04-2026
6    18-03-2025
7    21-10-2003
8    13-11-2001
9    05-04-2019

          Name              Bank Name  Bank Account  Age  Gender Creation_Date
0  AbdulRehman               Payoneer        237563   23    Male    23-04-2023
1       Fatima                    UBL        234598   27  Female    24-07-2022
2         Umar                 Meezan        237682   26    Male    09-05-2020
3       Taimur                    HBL        346778   21    Male    12-08-2025
4        Javed                 Askari       8667321   26    Male    17-12-2017
5    Alexander               Payoneer        876626   28    Male    02-04-2026
6        Maria               Payoneer       1237546   23  Female    18-03-2025
7       Miller           British Bank       8754456   42    Male    21-10-2003
8         Alex  National Bank Chicago       2314508   47    Male    13-11-2001
9       Zennat                 Meezan      86625591   31  Female    05-04-2019

In [18]:
# Because in majority of cases the data od missing values containing particular columns are very impotant so deleting full missing value
# containing columns or rows in dataset is not good approach. The good approach is to fill these missing values in dataset by fillna method.
# For this purpose I again used my housing_dataset.csv

print(df)

df.isnull().sum()

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [21]:
# You can either assign default value to every missing value in dataset by fillna() method.
# Like df.fillna(0, inplace=True)
# But the more professional way is to put calculated value to every place of missing value in dataset. For this, we shoulf se;ect the column in 
# which the missing values then with respect to situation either that column contains numerical values or object(string) values so you put 
# calculated value in places of missing values of particular column of dataset.

df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].mean(), inplace=True)

df.isnull().sum()

C:\Users\DELL\AppData\Local\Temp\ipykernel_3180\2684087374.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].mean(), inplace=True)

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [29]:
# Now I move on to inter-pollation in pandas. So in this terminology, we actually put estimated (means frequent according to flow of data)
# value in missing values of dataset.

# So actually there are many types of Inter collation algorithms like linear interpollation and binomial interpollation , time series interpolation 
# and also other 8 to 9 types famous interpolation techniques or algorithms in Pandas.

# 1. Preserve Data Integrity.
# 2. Smooth trends(So actually its predicts arbitrary numbers like predictable numbers in missing value in dataset).
# 3. No loss of data.

# So in pandas we use interpolate() method for filling estimated values in missing data velues in dataset instead of deleting paticular missing
# vlaues containing rows or columns or putting default values. Its actually also good approach as compare to filling with calculated values like
# with mean() or mode() or medium specially where we need data thats actually predictable.

# Linear Interpolation :

# First lets create a dataset :

Data3 = {
    'Time' : [7, 12, None, 22, 27, None, 37, 42],
    'Value' : [12, 24, None, 48, None, 72, None, 96]
}

df3 = pd.DataFrame(Data3)

print(df3)

   Time  Value
0   7.0   12.0
1  12.0   24.0
2   NaN    NaN
3  22.0   48.0
4  27.0    NaN
5   NaN   72.0
6  37.0    NaN
7  42.0   96.0

In [30]:
# Now lets apply Linear interpolation :

df3['Value'] = df3['Value'].interpolate(method="linear")

print(df3)

   Time  Value
0   7.0   12.0
1  12.0   24.0
2   NaN   36.0
3  22.0   48.0
4  27.0   60.0
5   NaN   72.0
6  37.0   84.0
7  42.0   96.0