In [1]:
# Now I talk about merging and sorting :

import pandas as pd

In [11]:
df1 = pd.read_csv('DataSets&DataFiles/credit_card.csv')

df1

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use_Chip,Exp_Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87,1/1/2023,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0
1,708987683,Blue,445,1,108,1/1/2023,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0
2,708084558,Blue,140,0,106,1/1/2023,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0
3,708085458,Blue,250,1,150,1/1/2023,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0
4,708086958,Blue,320,1,106,1/1/2023,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,Blue,340,1,106,12/24/2023,Week-52,Q4,2023,34516.0,1329,3906,77,0.039,Swipe,Fuel,546.84,0
10104,827703258,Blue,395,1,104,12/24/2023,Week-52,Q4,2023,13426.0,0,4674,66,0.000,Swipe,Grocery,607.62,0
10105,827712108,Blue,125,1,107,12/24/2023,Week-52,Q4,2023,2346.0,1373,4432,72,0.585,Swipe,Bills,797.76,0
10106,827888433,Blue,410,0,96,12/24/2023,Week-52,Q4,2023,6648.0,2242,2089,60,0.337,Swipe,Bills,146.23,0
10107,827890758,Blue,100,0,43,12/24/2023,Week-52,Q4,2023,2062.0,1302,3785,63,0.631,Chip,Bills,1059.80,0

In [12]:
df2 = pd.read_csv('DataSets&DataFiles/customer.csv')

df2

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084648,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,44,M,3,Graduate,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5
10104,827703258,48,M,3,Unknown,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3
10105,827712108,47,M,4,Graduate,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3
10106,827888433,42,F,3,Graduate,Married,TX,91750,no,no,no,cellular,White-collar,21390,4
10107,827890758,47,M,4,High School,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4

In [14]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 10108 entries, 0 to 10107
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Client_Num             10108 non-null  int64
 1   Card_Category          10108 non-null  str
 2   Annual_Fees            10108 non-null  int64
 3   Activation_30_Days     10108 non-null  int64
 4   Customer_Acq_Cost      10108 non-null  int64
 5   Week_Start_Date        10108 non-null  str
 6   Week_Num               10108 non-null  str
 7   Qtr                    10108 non-null  str
 8   current_year           10108 non-null  int64
 9   Credit_Limit           10108 non-null  float64
 10  Total_Revolving_Bal    10108 non-null  int64
 11  Total_Trans_Amt        10108 non-null  int64
 12  Total_Trans_Vol        10108 non-null  int64
 13  Avg_Utilization_Ratio  10108 non-null  float64
 14  Use_Chip               10108 non-null  str
 15  Exp_Type               10108 non-null  str
 16  Interest_Earned        10108 non-null  float64
 17  Delinquent_Acc         10108 non-null  int64
dtypes: float64(3), int64(9), str(6)
memory usage: 1.4 MB

In [15]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 10108 entries, 0 to 10107
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Client_Num               10108 non-null  int64
 1   Customer_Age             10108 non-null  int64
 2   Gender                   10108 non-null  str
 3   Dependent_Count          10108 non-null  int64
 4   Education_Level          10108 non-null  str
 5   Marital_Status           10108 non-null  str
 6   state_cd                 10108 non-null  str
 7   Zipcode                  10108 non-null  int64
 8   Car_Owner                10108 non-null  str
 9   House_Owner              10108 non-null  str
 10  Personal_loan            10108 non-null  str
 11  contact                  10108 non-null  str
 12  Customer_Job             10108 non-null  str
 13  Income                   10108 non-null  int64
 14  Cust_Satisfaction_Score  10108 non-null  int64
dtypes: int64(6), str(9)
memory usage: 1.2 MB

In [16]:
# Now apply merge and join methods :

df_merged = pd.merge(df1, df2, on="Client_Num", how="outer")

print("Outer Join : ")
df_merged

Outer Join :

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,...,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,Blue,200.0,0.0,87.0,1/1/2023,Week-1,Q1,2023.0,3544.0,...,Single,FL,91750.0,no,yes,no,unknown,Businessman,202326.0,3.0
1,708083283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Married,NJ,91750.0,no,no,no,cellular,Selfemployeed,5225.0,2.0
2,708084558,Blue,140.0,0.0,106.0,1/1/2023,Week-1,Q1,2023.0,8258.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,708084648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Married,NJ,91750.0,yes,no,no,unknown,Selfemployeed,14235.0,2.0
4,708085458,Blue,250.0,1.0,150.0,1/1/2023,Week-1,Q1,2023.0,1438.3,...,Single,NY,91750.0,no,no,no,cellular,Blue-collar,45683.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10105,827695683,Blue,340.0,1.0,106.0,12/24/2023,Week-52,Q4,2023.0,34516.0,...,Single,NV,91750.0,yes,yes,yes,unknown,Selfemployeed,44903.0,5.0
10106,827703258,Blue,395.0,1.0,104.0,12/24/2023,Week-52,Q4,2023.0,13426.0,...,Unknown,TX,91750.0,no,yes,no,cellular,Selfemployeed,73655.0,3.0
10107,827712108,Blue,125.0,1.0,107.0,12/24/2023,Week-52,Q4,2023.0,2346.0,...,Married,NY,91750.0,yes,no,no,cellular,Selfemployeed,62287.0,3.0
10108,827888433,Blue,410.0,0.0,96.0,12/24/2023,Week-52,Q4,2023.0,6648.0,...,Married,TX,91750.0,no,no,no,cellular,White-collar,21390.0,4.0
10109,827890758,Blue,100.0,0.0,43.0,12/24/2023,Week-52,Q4,2023.0,2062.0,...,Married,NY,91750.0,no,yes,no,cellular,Selfemployeed,42187.0,4.0

In [17]:
df_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 10110 entries, 0 to 10109
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Client_Num               10110 non-null  int64
 1   Card_Category            10108 non-null  str
 2   Annual_Fees              10108 non-null  float64
 3   Activation_30_Days       10108 non-null  float64
 4   Customer_Acq_Cost        10108 non-null  float64
 5   Week_Start_Date          10108 non-null  str
 6   Week_Num                 10108 non-null  str
 7   Qtr                      10108 non-null  str
 8   current_year             10108 non-null  float64
 9   Credit_Limit             10108 non-null  float64
 10  Total_Revolving_Bal      10108 non-null  float64
 11  Total_Trans_Amt          10108 non-null  float64
 12  Total_Trans_Vol          10108 non-null  float64
 13  Avg_Utilization_Ratio    10108 non-null  float64
 14  Use_Chip                 10108 non-null  str
 15  Exp_Type                 10108 non-null  str
 16  Interest_Earned          10108 non-null  float64
 17  Delinquent_Acc           10108 non-null  float64
 18  Customer_Age             10108 non-null  float64
 19  Gender                   10108 non-null  str
 20  Dependent_Count          10108 non-null  float64
 21  Education_Level          10108 non-null  str
 22  Marital_Status           10108 non-null  str
 23  state_cd                 10108 non-null  str
 24  Zipcode                  10108 non-null  float64
 25  Car_Owner                10108 non-null  str
 26  House_Owner              10108 non-null  str
 27  Personal_loan            10108 non-null  str
 28  contact                  10108 non-null  str
 29  Customer_Job             10108 non-null  str
 30  Income                   10108 non-null  float64
 31  Cust_Satisfaction_Score  10108 non-null  float64
dtypes: float64(16), int64(1), str(15)
memory usage: 2.5 MB

In [18]:
# Inner Joining :

df_merged2 = pd.merge(df1, df2, on="Client_Num", how="inner")

print("Inner Joing : ")
df_merged2

Inner Joing :

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,...,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,Blue,200,0,87,1/1/2023,Week-1,Q1,2023,3544.0,...,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708085458,Blue,250,1,150,1/1/2023,Week-1,Q1,2023,1438.3,...,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
2,708086958,Blue,320,1,106,1/1/2023,Week-1,Q1,2023,3128.0,...,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
3,708095133,Blue,100,0,94,1/1/2023,Week-1,Q1,2023,33304.0,...,Single,NY,91750,no,yes,no,cellular,Selfemployeed,14254,3
4,708098133,Blue,225,1,75,1/1/2023,Week-1,Q1,2023,2834.0,...,Single,CA,91750,yes,no,no,telephone,Selfemployeed,14975,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10101,827695683,Blue,340,1,106,12/24/2023,Week-52,Q4,2023,34516.0,...,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5
10102,827703258,Blue,395,1,104,12/24/2023,Week-52,Q4,2023,13426.0,...,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3
10103,827712108,Blue,125,1,107,12/24/2023,Week-52,Q4,2023,2346.0,...,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3
10104,827888433,Blue,410,0,96,12/24/2023,Week-52,Q4,2023,6648.0,...,Married,TX,91750,no,no,no,cellular,White-collar,21390,4
10105,827890758,Blue,100,0,43,12/24/2023,Week-52,Q4,2023,2062.0,...,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4

In [19]:
df_merged2.info()

<class 'pandas.DataFrame'>
RangeIndex: 10106 entries, 0 to 10105
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Client_Num               10106 non-null  int64
 1   Card_Category            10106 non-null  str
 2   Annual_Fees              10106 non-null  int64
 3   Activation_30_Days       10106 non-null  int64
 4   Customer_Acq_Cost        10106 non-null  int64
 5   Week_Start_Date          10106 non-null  str
 6   Week_Num                 10106 non-null  str
 7   Qtr                      10106 non-null  str
 8   current_year             10106 non-null  int64
 9   Credit_Limit             10106 non-null  float64
 10  Total_Revolving_Bal      10106 non-null  int64
 11  Total_Trans_Amt          10106 non-null  int64
 12  Total_Trans_Vol          10106 non-null  int64
 13  Avg_Utilization_Ratio    10106 non-null  float64
 14  Use_Chip                 10106 non-null  str
 15  Exp_Type                 10106 non-null  str
 16  Interest_Earned          10106 non-null  float64
 17  Delinquent_Acc           10106 non-null  int64
 18  Customer_Age             10106 non-null  int64
 19  Gender                   10106 non-null  str
 20  Dependent_Count          10106 non-null  int64
 21  Education_Level          10106 non-null  str
 22  Marital_Status           10106 non-null  str
 23  state_cd                 10106 non-null  str
 24  Zipcode                  10106 non-null  int64
 25  Car_Owner                10106 non-null  str
 26  House_Owner              10106 non-null  str
 27  Personal_loan            10106 non-null  str
 28  contact                  10106 non-null  str
 29  Customer_Job             10106 non-null  str
 30  Income                   10106 non-null  int64
 31  Cust_Satisfaction_Score  10106 non-null  int64
dtypes: float64(3), int64(14), str(15)
memory usage: 2.5 MB

In [ ]:
df_merged3 = pd.merge(df1, df2, on="Client_Num", how="left")

print("Left Joing : ")
df_merged3

Left Joing :

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,...,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,Blue,200,0,87,1/1/2023,Week-1,Q1,2023,3544.0,...,Single,FL,91750.0,no,yes,no,unknown,Businessman,202326.0,3.0
1,708987683,Blue,445,1,108,1/1/2023,Week-1,Q1,2023,3421.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,708084558,Blue,140,0,106,1/1/2023,Week-1,Q1,2023,8258.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,708085458,Blue,250,1,150,1/1/2023,Week-1,Q1,2023,1438.3,...,Single,NY,91750.0,no,no,no,cellular,Blue-collar,45683.0,1.0
4,708086958,Blue,320,1,106,1/1/2023,Week-1,Q1,2023,3128.0,...,Single,TX,91750.0,yes,yes,no,cellular,Businessman,59279.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,Blue,340,1,106,12/24/2023,Week-52,Q4,2023,34516.0,...,Single,NV,91750.0,yes,yes,yes,unknown,Selfemployeed,44903.0,5.0
10104,827703258,Blue,395,1,104,12/24/2023,Week-52,Q4,2023,13426.0,...,Unknown,TX,91750.0,no,yes,no,cellular,Selfemployeed,73655.0,3.0
10105,827712108,Blue,125,1,107,12/24/2023,Week-52,Q4,2023,2346.0,...,Married,NY,91750.0,yes,no,no,cellular,Selfemployeed,62287.0,3.0
10106,827888433,Blue,410,0,96,12/24/2023,Week-52,Q4,2023,6648.0,...,Married,TX,91750.0,no,no,no,cellular,White-collar,21390.0,4.0
10107,827890758,Blue,100,0,43,12/24/2023,Week-52,Q4,2023,2062.0,...,Married,NY,91750.0,no,yes,no,cellular,Selfemployeed,42187.0,4.0

In [ ]:
df_merged4 = pd.merge(df1, df2, on="Client_Num", how="right")

print("Right Joing : ")
df_merged4

Right Joing :

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,...,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,Blue,200.0,0.0,87.0,1/1/2023,Week-1,Q1,2023.0,3544.0,...,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,Blue,250.0,1.0,150.0,1/1/2023,Week-1,Q1,2023.0,1438.3,...,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,Blue,320.0,1.0,106.0,1/1/2023,Week-1,Q1,2023.0,3128.0,...,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,Blue,340.0,1.0,106.0,12/24/2023,Week-52,Q4,2023.0,34516.0,...,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5
10104,827703258,Blue,395.0,1.0,104.0,12/24/2023,Week-52,Q4,2023.0,13426.0,...,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3
10105,827712108,Blue,125.0,1.0,107.0,12/24/2023,Week-52,Q4,2023.0,2346.0,...,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3
10106,827888433,Blue,410.0,0.0,96.0,12/24/2023,Week-52,Q4,2023.0,6648.0,...,Married,TX,91750,no,no,no,cellular,White-collar,21390,4
10107,827890758,Blue,100.0,0.0,43.0,12/24/2023,Week-52,Q4,2023.0,2062.0,...,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4

In [25]:
Sample_df1 = df1.head(5)
Sample_df2 = df2.head(5)

df_merged5 = pd.merge(Sample_df1, Sample_df2, how="cross")

print("Cross Joing : ")
df_merged5

Cross Joing :

,Client_Num_x,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,...,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,Blue,200,0,87,1/1/2023,Week-1,Q1,2023,3544.0,...,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708082083,Blue,200,0,87,1/1/2023,Week-1,Q1,2023,3544.0,...,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708082083,Blue,200,0,87,1/1/2023,Week-1,Q1,2023,3544.0,...,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708082083,Blue,200,0,87,1/1/2023,Week-1,Q1,2023,3544.0,...,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708082083,Blue,200,0,87,1/1/2023,Week-1,Q1,2023,3544.0,...,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
5,708987683,Blue,445,1,108,1/1/2023,Week-1,Q1,2023,3421.0,...,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
6,708987683,Blue,445,1,108,1/1/2023,Week-1,Q1,2023,3421.0,...,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
7,708987683,Blue,445,1,108,1/1/2023,Week-1,Q1,2023,3421.0,...,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
8,708987683,Blue,445,1,108,1/1/2023,Week-1,Q1,2023,3421.0,...,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
9,708987683,Blue,445,1,108,1/1/2023,Week-1,Q1,2023,3421.0,...,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
10,708084558,Blue,140,0,106,1/1/2023,Week-1,Q1,2023,8258.0,...,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
11,708084558,Blue,140,0,106,1/1/2023,Week-1,Q1,2023,8258.0,...,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
12,708084558,Blue,140,0,106,1/1/2023,Week-1,Q1,2023,8258.0,...,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
13,708084558,Blue,140,0,106,1/1/2023,Week-1,Q1,2023,8258.0,...,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
14,708084558,Blue,140,0,106,1/1/2023,Week-1,Q1,2023,8258.0,...,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
15,708085458,Blue,250,1,150,1/1/2023,Week-1,Q1,2023,1438.3,...,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
16,708085458,Blue,250,1,150,1/1/2023,Week-1,Q1,2023,1438.3,...,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
17,708085458,Blue,250,1,150,1/1/2023,Week-1,Q1,2023,1438.3,...,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
18,708085458,Blue,250,1,150,1/1/2023,Week-1,Q1,2023,1438.3,...,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
19,708085458,Blue,250,1,150,1/1/2023,Week-1,Q1,2023,1438.3,...,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
20,708086958,Blue,320,1,106,1/1/2023,Week-1,Q1,2023,3128.0,...,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
21,708086958,Blue,320,1,106,1/1/2023,Week-1,Q1,2023,3128.0,...,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
22,708086958,Blue,320,1,106,1/1/2023,Week-1,Q1,2023,3128.0,...,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
23,708086958,Blue,320,1,106,1/1/2023,Week-1,Q1,2023,3128.0,...,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
24,708086958,Blue,320,1,106,1/1/2023,Week-1,Q1,2023,3128.0,...,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1

In [26]:
# Now the next topic is Concatenating the dataframes :

df_Customer1 = pd.read_excel('DataSets&DataFiles/df1_customers.xlsx')

df_Customer1

,CustomerID,Customer_Name,Age,Product,Product_Count,Price_Per_Product,Total_Price
0,C101,Imran Malik,56,Charger,2,661,1322
1,C102,Ali Chaudhry,46,Charger,2,2481,4962
2,C103,Zainab Sheikh,32,Mouse,4,3842,15368
3,C104,Bilal Malik,25,Speaker,4,1516,6064
4,C105,Farah Farooq,38,Printer,5,837,4185
5,C106,Ahmed Javed,56,Speaker,5,4493,22465
6,C107,Sana Khan,36,Printer,1,879,879
7,C108,Ali Malik,40,Monitor,5,2562,12810
8,C109,Usman Sheikh,28,Keyboard,5,564,2820
9,C110,Junaid Javed,28,Headphones,1,3068,3068
10,C111,Ali Farooq,41,Charger,1,2527,2527
11,C112,Usman Farooq,53,Tablet,3,891,2673
12,C113,Sana Sheikh,57,Mobile,3,4974,14922
13,C114,Tariq Javed,41,Laptop,5,4061,20305
14,C115,Hamza Khan,20,Mobile,2,3599,7198
15,C116,Shahid Butt,39,Headphones,1,3604,3604
16,C117,Adeel Iqbal,19,Headphones,5,3231,16155
17,C118,Faisal Chaudhry,41,Printer,3,2070,6210
18,C119,Bilal Sheikh,47,Speaker,1,3190,3190
19,C120,Shahid Raza,55,Mobile,1,1528,1528
20,C121,Ayesha Malik,19,Printer,2,1002,2004
21,C122,Kamran Malik,38,Printer,3,4988,14964
22,C123,Nida Raza,50,Speaker,2,1984,3968
23,C124,Sadia Chaudhry,29,Tablet,3,1363,4089
24,C125,Maryam Khan,39,Charger,1,1063,1063
25,C126,Iqra Aslam,42,Mouse,5,4691,23455
26,C127,Amna Malik,44,Charger,4,2257,9028
27,C128,Noor Iqbal,59,Laptop,5,2178,10890
28,C129,Ahmed Farooq,45,Mobile,3,1559,4677
29,C130,Mariam Javed,33,Charger,5,2222,11110

In [27]:
df_Customer2 = pd.read_excel("DataSets&DataFiles/df2_customers.xlsx")

df_Customer2

,CustomerID,Customer_Name,Age,Product,Product_Count,Price_Per_Product,Total_Price
0,C121,Kashif Raza,32,Mouse,3,3657,10971
1,C122,Waqas Sheikh,20,Monitor,4,3125,12500
2,C123,Adeel Malik,54,Mobile,2,2097,4194
3,C124,Sara Sheikh,24,Mouse,1,3560,3560
4,C125,Shahid Chaudhry,38,Printer,4,4127,16508
5,C126,Ahmed Sheikh,26,Headphones,4,2481,9924
6,C127,Sobia Malik,56,Tablet,3,2163,6489
7,C128,Kamran Chaudhry,35,Laptop,2,2538,5076
8,C129,Tariq Raza,21,Mouse,4,3802,15208
9,C130,Hina Raza,42,Charger,1,1806,1806
10,C131,Nida Sheikh,31,Headphones,1,3175,3175
11,C132,Farah Chaudhry,26,Charger,5,1782,8910
12,C133,Adeel Malik,43,Mobile,3,4913,14739
13,C134,Sadia Butt,19,Mouse,5,1163,5815
14,C135,Amna Sheikh,37,Charger,3,3945,11835
15,C136,Hina Aslam,45,Speaker,1,4263,4263
16,C137,Kamran Chaudhry,24,Keyboard,1,2353,2353
17,C138,Noor Farooq,25,Headphones,1,1791,1791
18,C139,Zainab Raza,52,Monitor,2,2136,4272
19,C140,Asad Khan,31,Headphones,1,3499,3499
20,C141,Zainab Khan,34,Charger,1,1198,1198
21,C142,Maryam Raza,53,Charger,1,4597,4597
22,C143,Kamran Chaudhry,57,Laptop,2,1354,2708
23,C144,Ahmed Sheikh,21,Speaker,5,3974,19870
24,C145,Noor Javed,19,Monitor,2,2207,4414
25,C146,Kashif Raza,23,Tablet,2,2233,4466
26,C147,Usman Aslam,59,Laptop,4,4010,16040
27,C148,Kamran Aslam,21,Mobile,3,3755,11265
28,C149,Bilal Chaudhry,46,Monitor,3,4996,14988
29,C150,Bilal Sheikh,35,Mouse,5,3431,17155

In [28]:
# Now we apply the concatenation :

# Vertical concatenation(Row Wise) :

df_Concat1 = pd.concat([df_Customer1, df_Customer2], axis=0, ignore_index=True)

df_Concat1

,CustomerID,Customer_Name,Age,Product,Product_Count,Price_Per_Product,Total_Price
0,C101,Imran Malik,56,Charger,2,661,1322
1,C102,Ali Chaudhry,46,Charger,2,2481,4962
2,C103,Zainab Sheikh,32,Mouse,4,3842,15368
3,C104,Bilal Malik,25,Speaker,4,1516,6064
4,C105,Farah Farooq,38,Printer,5,837,4185
5,C106,Ahmed Javed,56,Speaker,5,4493,22465
6,C107,Sana Khan,36,Printer,1,879,879
7,C108,Ali Malik,40,Monitor,5,2562,12810
8,C109,Usman Sheikh,28,Keyboard,5,564,2820
9,C110,Junaid Javed,28,Headphones,1,3068,3068
10,C111,Ali Farooq,41,Charger,1,2527,2527
11,C112,Usman Farooq,53,Tablet,3,891,2673
12,C113,Sana Sheikh,57,Mobile,3,4974,14922
13,C114,Tariq Javed,41,Laptop,5,4061,20305
14,C115,Hamza Khan,20,Mobile,2,3599,7198
15,C116,Shahid Butt,39,Headphones,1,3604,3604
16,C117,Adeel Iqbal,19,Headphones,5,3231,16155
17,C118,Faisal Chaudhry,41,Printer,3,2070,6210
18,C119,Bilal Sheikh,47,Speaker,1,3190,3190
19,C120,Shahid Raza,55,Mobile,1,1528,1528
20,C121,Ayesha Malik,19,Printer,2,1002,2004
21,C122,Kamran Malik,38,Printer,3,4988,14964
22,C123,Nida Raza,50,Speaker,2,1984,3968
23,C124,Sadia Chaudhry,29,Tablet,3,1363,4089
24,C125,Maryam Khan,39,Charger,1,1063,1063
25,C126,Iqra Aslam,42,Mouse,5,4691,23455
26,C127,Amna Malik,44,Charger,4,2257,9028
27,C128,Noor Iqbal,59,Laptop,5,2178,10890
28,C129,Ahmed Farooq,45,Mobile,3,1559,4677
29,C130,Mariam Javed,33,Charger,5,2222,11110
30,C121,Kashif Raza,32,Mouse,3,3657,10971
31,C122,Waqas Sheikh,20,Monitor,4,3125,12500
32,C123,Adeel Malik,54,Mobile,2,2097,4194
33,C124,Sara Sheikh,24,Mouse,1,3560,3560
34,C125,Shahid Chaudhry,38,Printer,4,4127,16508
35,C126,Ahmed Sheikh,26,Headphones,4,2481,9924
36,C127,Sobia Malik,56,Tablet,3,2163,6489
37,C128,Kamran Chaudhry,35,Laptop,2,2538,5076
38,C129,Tariq Raza,21,Mouse,4,3802,15208
39,C130,Hina Raza,42,Charger,1,1806,1806
40,C131,Nida Sheikh,31,Headphones,1,3175,3175
41,C132,Farah Chaudhry,26,Charger,5,1782,8910
42,C133,Adeel Malik,43,Mobile,3,4913,14739
43,C134,Sadia Butt,19,Mouse,5,1163,5815
44,C135,Amna Sheikh,37,Charger,3,3945,11835
45,C136,Hina Aslam,45,Speaker,1,4263,4263
46,C137,Kamran Chaudhry,24,Keyboard,1,2353,2353
47,C138,Noor Farooq,25,Headphones,1,1791,1791
48,C139,Zainab Raza,52,Monitor,2,2136,4272
49,C140,Asad Khan,31,Headphones,1,3499,3499
50,C141,Zainab Khan,34,Charger,1,1198,1198
51,C142,Maryam Raza,53,Charger,1,4597,4597
52,C143,Kamran Chaudhry,57,Laptop,2,1354,2708
53,C144,Ahmed Sheikh,21,Speaker,5,3974,19870
54,C145,Noor Javed,19,Monitor,2,2207,4414
55,C146,Kashif Raza,23,Tablet,2,2233,4466
56,C147,Usman Aslam,59,Laptop,4,4010,16040
57,C148,Kamran Aslam,21,Mobile,3,3755,11265
58,C149,Bilal Chaudhry,46,Monitor,3,4996,14988
59,C150,Bilal Sheikh,35,Mouse,5,3431,17155

In [29]:
# Horizontal concatenation(Column wise):

df_Concat2 = pd.concat([df_Customer1, df_Customer2], axis=1, ignore_index=True)

df_Concat2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,C101,Imran Malik,56,Charger,2,661,1322,C121,Kashif Raza,32,Mouse,3,3657,10971
1,C102,Ali Chaudhry,46,Charger,2,2481,4962,C122,Waqas Sheikh,20,Monitor,4,3125,12500
2,C103,Zainab Sheikh,32,Mouse,4,3842,15368,C123,Adeel Malik,54,Mobile,2,2097,4194
3,C104,Bilal Malik,25,Speaker,4,1516,6064,C124,Sara Sheikh,24,Mouse,1,3560,3560
4,C105,Farah Farooq,38,Printer,5,837,4185,C125,Shahid Chaudhry,38,Printer,4,4127,16508
5,C106,Ahmed Javed,56,Speaker,5,4493,22465,C126,Ahmed Sheikh,26,Headphones,4,2481,9924
6,C107,Sana Khan,36,Printer,1,879,879,C127,Sobia Malik,56,Tablet,3,2163,6489
7,C108,Ali Malik,40,Monitor,5,2562,12810,C128,Kamran Chaudhry,35,Laptop,2,2538,5076
8,C109,Usman Sheikh,28,Keyboard,5,564,2820,C129,Tariq Raza,21,Mouse,4,3802,15208
9,C110,Junaid Javed,28,Headphones,1,3068,3068,C130,Hina Raza,42,Charger,1,1806,1806
10,C111,Ali Farooq,41,Charger,1,2527,2527,C131,Nida Sheikh,31,Headphones,1,3175,3175
11,C112,Usman Farooq,53,Tablet,3,891,2673,C132,Farah Chaudhry,26,Charger,5,1782,8910
12,C113,Sana Sheikh,57,Mobile,3,4974,14922,C133,Adeel Malik,43,Mobile,3,4913,14739
13,C114,Tariq Javed,41,Laptop,5,4061,20305,C134,Sadia Butt,19,Mouse,5,1163,5815
14,C115,Hamza Khan,20,Mobile,2,3599,7198,C135,Amna Sheikh,37,Charger,3,3945,11835
15,C116,Shahid Butt,39,Headphones,1,3604,3604,C136,Hina Aslam,45,Speaker,1,4263,4263
16,C117,Adeel Iqbal,19,Headphones,5,3231,16155,C137,Kamran Chaudhry,24,Keyboard,1,2353,2353
17,C118,Faisal Chaudhry,41,Printer,3,2070,6210,C138,Noor Farooq,25,Headphones,1,1791,1791
18,C119,Bilal Sheikh,47,Speaker,1,3190,3190,C139,Zainab Raza,52,Monitor,2,2136,4272
19,C120,Shahid Raza,55,Mobile,1,1528,1528,C140,Asad Khan,31,Headphones,1,3499,3499
20,C121,Ayesha Malik,19,Printer,2,1002,2004,C141,Zainab Khan,34,Charger,1,1198,1198
21,C122,Kamran Malik,38,Printer,3,4988,14964,C142,Maryam Raza,53,Charger,1,4597,4597
22,C123,Nida Raza,50,Speaker,2,1984,3968,C143,Kamran Chaudhry,57,Laptop,2,1354,2708
23,C124,Sadia Chaudhry,29,Tablet,3,1363,4089,C144,Ahmed Sheikh,21,Speaker,5,3974,19870
24,C125,Maryam Khan,39,Charger,1,1063,1063,C145,Noor Javed,19,Monitor,2,2207,4414
25,C126,Iqra Aslam,42,Mouse,5,4691,23455,C146,Kashif Raza,23,Tablet,2,2233,4466
26,C127,Amna Malik,44,Charger,4,2257,9028,C147,Usman Aslam,59,Laptop,4,4010,16040
27,C128,Noor Iqbal,59,Laptop,5,2178,10890,C148,Kamran Aslam,21,Mobile,3,3755,11265
28,C129,Ahmed Farooq,45,Mobile,3,1559,4677,C149,Bilal Chaudhry,46,Monitor,3,4996,14988
29,C130,Mariam Javed,33,Charger,5,2222,11110,C150,Bilal Sheikh,35,Mouse,5,3431,17155