In [1]:
# lets explore the functionality of rows in pandas :

# Now I use .head() to show first rows of dataset if cannot pass any n number other as on basis of my n number :
import pandas as pd

df = pd.read_csv('Data_sources&Data_sets/customer.csv')

df

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,44,M,3,Graduate,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5
10104,827703258,48,M,3,Unknown,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3
10105,827712108,47,M,4,Graduate,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3
10106,827888433,42,F,3,Graduate,Married,TX,91750,no,no,no,cellular,White-collar,21390,4
10107,827890758,47,M,4,High School,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4

In [2]:
df.head() # By default print first five rows if I caanot specify any n rows in function head()

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1

In [3]:
df.head(12) # Then in this situation its shows first 12 rows because n = 12

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
5,708095133,33,F,1,High School,Single,NY,91750,no,yes,no,cellular,Selfemployeed,14254,3
6,708098133,34,F,3,Graduate,Single,CA,91750,yes,no,no,telephone,Selfemployeed,14975,2
7,708099183,34,F,2,Uneducated,Single,CA,91750,no,no,no,cellular,Retirees,31982,2
8,708100533,48,M,2,High School,Married,NJ,91750,yes,no,no,telephone,Businessman,86668,2
9,708103608,53,F,1,Graduate,Married,NJ,91750,yes,yes,no,cellular,Businessman,223196,1
10,708104658,31,F,0,Post-Graduate,Single,CA,91750,no,yes,no,telephone,Businessman,33625,2
11,708108333,34,F,4,Graduate,Single,NY,91750,no,no,no,cellular,Selfemployeed,14975,3

In [4]:
df.tail()  # Same as like in tail.

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
10103,827695683,44,M,3,Graduate,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5
10104,827703258,48,M,3,Unknown,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3
10105,827712108,47,M,4,Graduate,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3
10106,827888433,42,F,3,Graduate,Married,TX,91750,no,no,no,cellular,White-collar,21390,4
10107,827890758,47,M,4,High School,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4

In [5]:
df.tail(13) # Same as in tail as like when I specify n = 13 means last 13 rows of dataset.

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
10095,827476983,54,F,0,Doctorate,Single,TX,91750,yes,yes,no,cellular,Govt,17285,3
10096,827619933,39,F,4,Unknown,Married,NJ,91750,yes,no,no,cellular,Selfemployeed,38548,4
10097,827628408,49,F,1,Uneducated,Single,CA,91750,no,yes,yes,cellular,Businessman,40188,5
10098,827631483,52,F,3,Graduate,Single,IL,91750,yes,yes,no,unknown,Blue-collar,20787,5
10099,827635083,39,M,2,High School,Married,TX,91750,no,yes,no,cellular,Govt,54181,5
10100,827643858,44,F,2,Unknown,Unknown,FL,91750,no,yes,no,telephone,Selfemployeed,35540,5
10101,827683383,42,F,3,Uneducated,Married,TX,91750,no,yes,yes,cellular,Businessman,228308,3
10102,827691858,46,F,5,Graduate,Married,NY,91750,yes,no,no,unknown,Selfemployeed,20071,3
10103,827695683,44,M,3,Graduate,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5
10104,827703258,48,M,3,Unknown,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3
10105,827712108,47,M,4,Graduate,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3
10106,827888433,42,F,3,Graduate,Married,TX,91750,no,no,no,cellular,White-collar,21390,4
10107,827890758,47,M,4,High School,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4